// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomPlugin","status":true,"description":"Custom Text Box Plugin with Click to Show and Hide","parameters":{"textBoxWidth":"400","textBoxHeight":"200","textBoxX":"208","textBoxY":"500","textBoxBackground":""}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}}
];
